[package]
name = "autosurgeon"
description = "A library for working with data in automerge documents"
version = "0.2.2"
edition = "2021"
authors = ["Alex Good <alex@memoryandthought.me>"]
license = "MIT"
rust-version = "1.65.0"
repository = "https://github.com/alexjg/autosurgeon"
readme = "../README.md"

[dependencies]
#automerge = { version = "^0.2" }
automerge = { path = "../../automerge-rs/rust/automerge" }
thiserror = "1.0.37"
smol_str = { version = "^0.1.21" }
autosurgeon-derive = { path = "../autosurgeon-derive", version = "0.2.2" }
similar = "2.2.1"
uuid = { version = "1.2.2", optional = true }

[dev-dependencies]
#automerge-test = "^0.1"
automerge-test = { path = "../../automerge-rs/rust/automerge-test" }

[features]
uuid = ["dep:uuid"]
