[package]
name = "autosurgeon-derive"
description = "Procedural macros for implementing autosurgeon"
version = "0.2.2"
edition = "2021"
authors = ["Alex Good <alex@memoryandthought.me>"]
license = "MIT"
rust-version = "1.65.0"
repository = "https://github.com/alexjg/autosurgeon"

[lib]
proc_macro = true

[dependencies]
quote = "1.0.21"
syn = "1.0.103"
proc-macro2 = "1.0"
smol_str = { version = "^0.1.21" }
thiserror = "1.0.37"

[dev-dependencies]
autosurgeon = { path = "../autosurgeon" }
#automerge = { version = "^0.2" }
automerge = { path = "../../automerge-rs/rust/automerge" }
#automerge-test = "^0.1"
automerge-test = { path = "../../automerge-rs/rust/automerge-test" }
